const words = [
    // Fruits & Foods
    "apple", "banana", "orange", "grape", "mango", "pear", "peach", "cherry", "strawberry", "blueberry",
    "kiwi", "lemon", "lime", "pineapple", "watermelon", "coconut", "fig", "papaya", "plum", "pomegranate",
    "avocado", "broccoli", "carrot", "lettuce", "tomato", "cucumber", "pumpkin", "radish", "zucchini", "asparagus",
    "cheese", "bacon", "butter", "yogurt", "chocolate", "vanilla", "caramel", "honey", "marshmallow", "almond", "croissant", "bagel", "waffle", "pancake", "donut", "macaron", "pretzel", "sushi", "taco", "burrito", "cereal", "oatmeal", "spaghetti", "lasagna", "steak", "hamburger", "hotdog", "pudding", "gelato", "sorbet", "pomegranate", "blackberry", "raspberry", "cranberry", "apricot", "boysenberry", "date", "elderberry", "gooseberry", "mushroom", "spinach",  "artichoke", "garlic", "onion", "cabbage", "ginger", "chili", "kiwifruit", "watercress", "okra", "fennel", "celery", "beetroot", "acorn squash", "butternut", "cantaloupe", "blackberry", "fruitcake", "cinnamon", "saffron", "pepper", "oregano", "cilantro", "sage", "thyme","salt", "peppercorn", "clove", "rosemary", "basil", "turmeric", "salmon", "pasta", "vegan", "smoothie", "syrup", "tofu", "tapioca", "shrimp", "sauerkraut", "peanut", "poppy seed", "balsamic", "ketchup", "mustard", "mayonnaise", "potato", "toast", "salsa", "gouda", "brie", "olive", "coffee", "walnut", "aubergine", "eggplant", 

    // Animals
    "elephant", "giraffe", "rhinoceros", "hippopotamus", "crocodile", "alligator", "newt", "salamander", "scorpion", "tarantula", "stingray", "jellyfish", "seahorse", "parakeet", "cockatoo", "viper", "anaconda", "iguana", "komodo dragon", "piranha", "walrus", "lion", "caribou", "reindeer", "yak", "emu", "cassowary", "beaver", "weasel", "stoat", "lynx", "ocelot", "snow leopard", "mandrill", "orangutan", "chimpanzee", "gorilla", "pangolin", "sloth", "tapir", "wolfhound", "mastodon", "megalodon", "firefly", "honeybee", "manta ray", "puffin", "civet", "axolotl", "narwhal",
    
    // Nature & Space
    "asterism", "constellation", "asteroid", "meteor", "exosphere", "ionosphere", "heliopause", "magnetotail", "lithosphere", "mantle", "crust", "tectonic", "biosphere", "ecosphere", "biome", "ecosystem", "cryosphere", "permafrost", "ice cap", "glacier", "thermosphere", "magnetopause", "plasma layer", "solar", "troposphere", "weather", "cloud", "stratosphere", "ozone", "stratopause", "mesosphere", "mesopause", "exoplanet", "planet", "gas", "Earth", "supercluster", "galactic filament", "galaxy cluster", "local group", "interstellar", "nebula", "intergalactic", "cosmic void", "quark", "gluon", "lepton", "neutrino", "cosmic", "graviton", "astrononaut", "ergosphere", "photon sphere", "singularity", "spacetime", "wormhole", "cosmology", "astrophysics", "astrochemistry", "astrobiology", "magnetosphere", "thermocline", "halocline", "pycnocline", "seamount", "isthmus", "peninsula", "land bridge", "barrier spit", "archipelago", "island", "atoll", "coral", "badlands", "desert", "hoodoo", "wash", "delta", "estuary", "river", "drumlin", "esker", "gorge", "canyon", "ravine", "sinkhole", "cenote", "doline", "fumarole", "geyser", "basin", "depression", "graben", "endorheic lake", "mesa", "plateau", "tableland", "upland", "butte", "monadnock", "inselberg", "rock spire", "karst", "fjord", "reef", 

    
    // Fantasy & Mysticism
    "sigil", "rune", "glyph", "inscription", "etheric", "astral", "spiritual", "ethereal", "phantasmagoria", "mirage", "illusion", "spectral", "eldritch", "otherworldly", "cosmic horror", "unfathomable", "wyrm", "drake", "dragon", "wyvern", "sorcerer", "enchanter", "mage", "warlock",  "necropolis", "catacombs", "tomb", "crypt", "levitation", "telekinesis", "flight", "aerial", "arcadia", "elysium", "paradise", "realm", "chimera", "griffin","manticore", "hippogriff", "shade", "wraith", "wight", "ghost", "specter", "banshee", "phantom", "spirit", "eidolon", "revenant", "apparition", "shade", "shaman", "witch doctor", "medicine man", "healer", "thaumaturgy", "spellcraft", "magic", "sorcery", "mana", "aether", "arcane", "soulforce", "ragnarok", "apocalypse", "eldritch", "netherborn", "voidspawn", "abyssal", "golem", "homunculus", "automaton", "construct", "doppelganger", "changeling", "shapeshifter", "paladin", "templar", "crusader", "warlock", "hexer", "sorcerer", "occultist", "summoner", "conjurer", "necromancer", "invoker", "seer", "diviner", "oracle", "prophet", "divination", "augury", "oracles", "foretelling", "luminous", "glimmering", "radiant", "eldar", "fae", "dryad", "nymph", "arcane", "occult", "mystic", "enchanted", "mythic", "legendary", "heroic", "epic", "immortal", "divine", "demigod", "celestial",

    
    // Science & Technology
    "hyperloop", "vacuum train", "maglev", "transport", "cybernetics", "robotics", "AI", "bio-robotics", "antimatter", "antiproton", "positron", "exabyte", "zettabyte", "petabyte", "terabyte", "qubit", "computer", "quantum", "superposition", "bioinformatics", "biology", "genomics", "proteomics", "genome", "CRISPR", "gene", "biotechnology", "bioengineering", "bionics", "prosthetics", "biomechanics", "fusion", "nuclear", "tokamak", "blockchain", "cryptocurrency", "nanomaterial", "nanotechnology", "graphene", "superposition", "holographic", "hologram", "3D",  "drone", "optogenetics", "supercomputer", "biomechanics", "ergonomics", "haptic", "drone", "autonomous", "metaverse", "virtual universe", "cryonics", "cryopreservation", "exoskeleton", "aerodynamics", "hydrodynamics", "airflow", "transhumanism",
    
    // Colors & Light
    "ultramarine", "azure", "cinnabar", "vermilion", "scarlet", "crimson", "gamboge", "amber", "goldenrod", "marigold", "malachite", "emerald", "jade", "coquelicot", "red", "perse", "blue", "indigo", "violet", "feldgrau", "khaki", "glaucous", "smalt", "lavender", "amethyst", "amaranth", "fuchsia", "magenta", "bistre", "umber", "brown", "vermilion", "scarlet", "cinnabar", "cardinal", "harlequin", "chartreuse", "sanguine", "rust", "terracotta", "tawny", "caramel", "sienna", "viridian", "pistachio", "wisteria", "lavender", "mauve", "periwinkle", "xanadu", "sage", "asparagus", "zinnwaldite", "taupe", "putty", "drab", "heliotrope", "purple-pink", "orchid", "violet red", "carmine", "crimson", "ruby red", "burgundy", "umber", "sepia", "tan", "beige", "salmon", "peach", "lemon", "buttercup", "saffron", "sunflower", "sapphire", "royal blue", "navy", "burgundy", "charcoal", "graphite", "slate", 

];

// Export the words array (only needed if using ES6 modules)
if (typeof module !== "undefined") {
    module.exports = words;
}
