const words = [
    // Fruits & Foods
    "apple", "banana", "orange", "grape", "mango", "pear", "peach", "cherry", "strawberry", "blueberry",
    "kiwi", "lemon", "lime", "pineapple", "watermelon", "coconut", "fig", "papaya", "plum", "pomegranate",
    "avocado", "broccoli", "carrot", "lettuce", "tomato", "cucumber", "pumpkin", "radish", "zucchini", "asparagus",
    "cheese", "bacon", "butter", "yogurt", "chocolate", "vanilla", "caramel", "honey", "marshmallow", "almond",
    "croissant", "bagel", "waffle", "pancake", "donut", "macaron", "pretzel", "sushi", "taco", "burrito",
    "cereal", "oatmeal", "spaghetti", "lasagna", "steak", "hamburger", "hotdog", "pudding", "gelato", "sorbet",
    "pomegranate", "plum", "blackberry", "raspberry", "cranberry", "apricot", "boysenberry", "date", "elderberry", "gooseberry",
    "avocado", "mushroom", "spinach", "brussels sprout", "artichoke", "garlic", "onion", "cabbage", "ginger", "chili",
    "coconut water", "kiwi fruit", "watercress", "okra", "fennel", "asparagus", "celery", "beetroot", "acorn squash", "butternut squash",
    "cantaloupe", "blackberry", "fruitcake", "cinnamon", "saffron", "pepper", "oregano", "cilantro", "sage", "thyme",
    "chili pepper", "peppercorn", "fennel seed", "clove", "bay leaf", "rosemary", "basil", "garlic clove", "ginger root", "turmeric",
    "salmon", "pasta", "vegan", "smoothie", "syrup", "tofu", "tapioca", "shrimp", "sauerkraut", "peanut butter",
    "poppy seed", "balsamic", "ketchup", "mustard", "mayonnaise", "sweet potato", "avocado toast", "mango salsa", "gouda", "brie",

    // Animals
    "elephant", "giraffe", "rhinoceros", "hippopotamus", "crocodile", "alligator", "newt", "salamander", "scorpion", "tarantula",
    "stingray", "jellyfish", "seahorse", "parakeet", "cockatoo", "viper", "anaconda", "iguana", "komodo dragon", "piranha",
    "walrus", "sea lion", "caribou", "reindeer", "yak", "emu", "cassowary", "beaver", "weasel", "stoat",
    "lynx", "ocelot", "snow leopard", "mandrill", "orangutan", "chimpanzee", "gorilla", "pangolin", "sloth", "tapir",
    "wolfhound", "mastodon", "megalodon", "firefly", "honeybee", "manta ray", "puffin", "civet", "axolotl", "narwhal",
    
    // Nature & Space
    "asterism", "constellation", "asteroid belt", "meteor shower", "exosphere", "ionosphere", "heliopause", "magnetotail", "lithosphere", "mantle", "crust", "tectonic plate", "biosphere", "ecosphere", "biome", "ecosystem", "cryosphere", "permafrost", "ice cap", "glacier", "thermosphere", "magnetopause", "plasma layer", "solar flare", "troposphere", "weather front", "cloud ceiling", "jet stream", "stratosphere", "ozone layer", "cirrus cloud", "stratopause",
    "mesosphere", "noctilucent clouds", "meteor trail", "mesopause", "exoplanet", "rogue planet", "gas giant", "super-Earth", "supercluster", "galactic filament", "galaxy cluster", "local group", "interstellar", "nebula", "intergalactic", "cosmic void", "quark", "gluon", "lepton", "neutrino", "dark energy", "dark matter", "vacuum energy", "cosmic inflation", "graviton", "Higgs boson", "string theory", "quantum foam", "light-year", "parsec", "astronomical unit", "cosmic distance", "event horizon", "black hole", "ergosphere", "photon sphere", "singularity", "spacetime", "white hole", "wormhole", "aurora borealis", "polar lights", "geomagnetic storm", "charged particles", "aurora australis", "southern lights", "ion storm", "solar wind", "cosmology", "astrophysics", "astrochemistry", "astrobiology", "magnetosphere", "solar wind", "geomagnetic field", "bow shock", "thermocline", "halocline", "pycnocline", "mixed layer", "ocean trench", "submarine canyon", "mid-ocean ridge", "seamount", "continental shelf", "continental slope", "abyssal plain", "ocean basin", "isthmus", "peninsula", "land bridge", "barrier spit", "archipelago", "island chain", "volcanic island", "coral atoll", "badlands", "desert pavement", "hoodoo", "wash", "delta", "alluvial fan", "estuary", "river mouth", "glacial moraine", "drumlin", "esker", "kettle lake", "gorge", "canyon", "ravine", "slot canyon", "tidal pool", "intertidal zone", "rocky shore", "coastal shelf", "sinkhole", "cenote", "doline", "karst window", "mud volcano", "fumarole", "hot spring", "geyser", "basin", "depression", "graben", "endorheic lake", "mesa", "plateau", "tableland", "upland", "butte", "monadnock", "inselberg", "rock spire", "karst", "limestone cave", "solution sinkhole", "karst tower", "fjord", "glacial valley", "sea inlet", "u-shaped valley", "atoll", "coral reef", "barrier reef", "fringing reef",

    
    // Fantasy & Mysticism
    "sigil", "rune", "glyph", "inscription", "etheric", "astral", "spiritual", "ethereal", "phantasmagoria", "mirage", "illusion", "spectral", "eldritch", "otherworldly", "cosmic horror", "unfathomable", "wyrm", "drake", "dragon", "wyvern", "sorcerer", "enchanter", "mage", "warlock",  "necropolis", "catacombs", "tomb", "crypt", "levitation", "telekinesis", "flight", "aerial", "arcadia", "elysium", "paradise", "heavenly realm", "chimera", "griffin", "manticore", "hippogriff",
    "shade", "wraith", "wight", "ghost", "specter", "banshee", "phantom", "spirit", "eidolon", "revenant", "apparition", "shade", "shaman", "witch doctor", "medicine man", "spiritual healer", "thaumaturgy", "spellcraft", "magic", "sorcery", "mana", "aether", "arcane energy", "soulforce", "ragnarok", "apocalypse", "end of days", "final battle", "eldritch", "netherborn", "voidspawn", "abyssal", "golem", "homunculus", "automaton", "construct", "doppelganger", "changeling", "mirror self", "shapeshifter",
    "paladin", "templar", "crusader", "holy knight", "warlock", "hexer", "sorcerer", "occultist", "summoner", "conjurer", "necromancer", "invoker", "seer", "diviner", "oracle", "prophet", "divination", "augury", "oracles", "foretelling", "ethereal", "luminous", "glimmering", "radiant", "eldar", "fae", "dryad", "nymph", "arcane", "occult", "mystic", "enchanted", "mythic", "legendary", "heroic", "epic", "immortal", "divine", "demigod", "celestial",

    
    // Science & Technology
    "hyperloop", "vacuum train", "maglev", "transportation innovation", "cybernetics", "robotics", "artificial intelligence", "bio-robotics", "antimatter", "dark matter", "antiproton", "positron", "exabyte", "zettabyte", "petabyte", "terabyte", "qubit", "quantum computer", "quantum bit", "superposition", "bioinformatics", "computational biology", "genomics", "proteomics", "gene editing", "CRISPR", "gene therapy", "genetic modification", "synthetic biology", "biotechnology", "bioengineering", "biomolecular design", "bionics", "prosthetics", "cybernetic enhancement", "biomechanics", "fusion reactor", "nuclear fusion", "tokamak", "fusion power plant",
    "blockchain", "decentralized ledger", "cryptocurrency", "smart contract", "nanomaterial", "nanotechnology", "carbon nanotube", "graphene", "quantum entanglement", "quantum teleportation", "superposition", "quantum cryptography", "holographic", "hologram", "virtual reality", "3D projection",
    "autonomous vehicle", "self-driving car", "driverless technology", "autonomous drone", "singularity theory", "technological singularity", "AI explosion", "intelligence explosion", "deep learning", "machine learning", "reinforcement learning", "augmented reality", "mixed reality", "virtual reality", "immersive technology", "neural network", "artificial neural network", "deep neural network", "cognitive computing", "optogenetics", "genetically modified organisms", "light-controlled proteins", "neural manipulation", "supercomputer", "quantum computer", "high-performance computing", "parallel processing", "biomechanics", "ergonomics", "sports science", "human performance optimization", "haptic", "haptic feedback", "force feedback", "tactile technology", "drone", "unmanned aerial vehicle", "delivery drone", "autonomous flying vehicle", "machine learning", "artificial intelligence", "predictive analytics", "algorithmic decision-making", "metaverse", "virtual universe", "digital realm", "immersive world", "cryonics", "cryopreservation", "suspended animation", "frozen state", "exoskeleton", "powered suit", "wearable robotics", "human augmentation", "aerodynamics", "fluid dynamics", "airflow", "wind tunnel", "transhumanism", "human enhancement", "post-human", "biotechnological evolution",

    
    // Colors & Light
    "ultramarine", "lapis lazuli", "cobalt blue", "azure", "cinnabar", "vermilion", "scarlet", "crimson", "gamboge", "amber", "goldenrod", "marigold", "malachite", "emerald", "jade", "mint green", "coquelicot", "vermillion red", "cherry red", "tomato red", "perse", "blue-violet", "indigo", "violet", "feldgrau", "olive drab", "army green", "khaki", "glaucous", "dusty blue", "slate gray", "misty blue", "smalt", "Prussian blue", "midnight blue", "deep navy", "tyrian purple", "royal purple", "lavender", "amethyst", "amaranth", "rose red", "fuchsia", "magenta", "bistre", "umber", "brown", "chocolate", "vermilion", "scarlet", "cinnabar", "cardinal", "harlequin", "lime green", "chartreuse", "apple green", "sanguine", "rust", "burnt orange", "terracotta", "tawny", "light brown", "caramel", "sienna", "viridian", "sea green", "forest green", "pistachio", "wisteria", "lavender", "mauve", "periwinkle", "xanadu", "sage", "olive", "asparagus", "zinnwaldite", "taupe", "putty", "drab", "heliotrope", "purple-pink", "orchid", "violet red", "carmine", "crimson", "ruby red", "burgundy", "umber", "chocolate brown", "coffee", "walnut", "sepia", "antique brown", "tan", "beige", "coral pink", "salmon", "peach", "blush pink", "cadmium yellow", "canary yellow", "lemon", "buttercup", "saffron", "golden yellow", "mustard", "sunflower", "sapphire", "royal blue", "navy", "steel blue", "aubergine", "eggplant", "plum", "burgundy", "charcoal", "graphite", "slate", "charcoal gray",

];

// Export the words array (only needed if using ES6 modules)
if (typeof module !== "undefined") {
    module.exports = words;
}
